# Generated by Django 2.0.4 on 2018-07-24 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('birthday', models.DateField()),
                ('cellphone', models.CharField(max_length=64, verbose_name='Celular')),
                ('gender', models.CharField(max_length=64, verbose_name='Sexo')),
                ('civil_status', models.CharField(max_length=64, verbose_name='Status Civil')),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(blank=True, max_length=64, null=True, verbose_name='Secret Key')),
                ('email', models.CharField(max_length=64, verbose_name='E-mail')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuário Comprador+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=64, verbose_name='Sexo')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('birthday', models.DateField()),
                ('related_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Parentesco com+', to='buyerprofile.BuyerProfile')),
            ],
        ),
    ]
