# Generated by Django 2.0.4 on 2018-08-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='buyerprofile/photo', verbose_name='Foto'),
        ),
    ]
