# Generated by Django 2.0.4 on 2018-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0003_buyerprofile_accepts_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='relation',
            field=models.CharField(default=1, max_length=64, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
