# Generated by Django 2.0.4 on 2018-11-01 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0014_auto_20181029_1250'),
        ('buyerprofile', '0005_auto_20180826_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyerprofile.BuyerProfile')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
    ]
