# Generated by Django 2.0.4 on 2018-11-01 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0007_auto_20181101_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='buyerprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='buyerprofile.BuyerProfile'),
        ),
    ]
