# Generated by Django 2.0.4 on 2018-11-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0009_auto_20181102_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='placeprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlacePrice'),
        ),
    ]
