# Generated by Django 2.0.4 on 2018-11-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0010_auto_20181102_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='buyerprofile',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='place',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='placeprice',
        ),
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
    ]
