# Generated by Django 2.0.4 on 2018-11-02 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0007_auto_20181102_1702'),
        ('placecore', '0018_auto_20181102_1711'),
        ('buyerprofile', '0011_auto_20181102_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerprofile.BuyerProfile')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
                ('placeprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlacePrice')),
            ],
        ),
    ]
