# Generated by Django 2.0.4 on 2018-11-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0012_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='cpf',
            field=models.CharField(default='408.570.728-03', max_length=32, verbose_name='CPF'),
        ),
    ]
