# Generated by Django 2.0.4 on 2018-11-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0013_buyerprofile_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='cpf',
            field=models.CharField(max_length=32, verbose_name='CPF'),
        ),
    ]
