# Generated by Django 2.0.4 on 2019-01-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0015_auto_20181203_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='cellphone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='civil_status',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Status Civil'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='cpf',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='buyerprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Sexo'),
        ),
    ]
