# Generated by Django 2.0.4 on 2019-01-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyerprofile', '0016_auto_20190119_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
