# Generated by Django 2.0.5 on 2018-07-08 01:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sellerprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoProvisory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='place/photoprovisory', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('relevance', models.FloatField(default=0, verbose_name='Relevância')),
                ('visualization', models.IntegerField(default=0, verbose_name='Visualizações')),
                ('name', models.CharField(max_length=64, verbose_name='Nome')),
                ('address', models.CharField(max_length=256, verbose_name='Endereço')),
                ('description', models.CharField(max_length=512, verbose_name='Descrição')),
                ('capacity', models.IntegerField(verbose_name='Capacidade')),
                ('size', models.FloatField(verbose_name='Tamanho')),
                ('video', models.CharField(max_length=128, verbose_name='Video URL')),
                ('children_rides', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('decoration', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('menu', models.FileField(upload_to='place/menu', verbose_name='Menu')),
                ('lat', models.FloatField(verbose_name='Latitude')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('sellerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerProfile', to='sellerprofile.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceAdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcoholic_drink', models.BooleanField(verbose_name='Serve bebidas alcólicas')),
                ('has_entertainment', models.BooleanField(verbose_name='Enterteinimento')),
                ('has_thematicdecoration', models.BooleanField(verbose_name='Decoração Temática')),
                ('has_childrenrides', models.BooleanField(verbose_name='Brinquedo pra Crianças')),
                ('has_costumes', models.BooleanField(verbose_name='Fantasias para os Atores')),
                ('has_parking', models.BooleanField(verbose_name='Estacionamento')),
                ('has_externalarea', models.BooleanField(verbose_name='Área externa')),
                ('has_music', models.BooleanField(verbose_name='Música')),
                ('has_illumination', models.BooleanField(verbose_name='Iluminação')),
                ('has_babychangingroom', models.BooleanField(verbose_name='Fraldário')),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PlacePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placecore.PhotoProvisory')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceVisualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
    ]
