# Generated by Django 2.0.4 on 2018-08-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=128, verbose_name='Endereço'),
        ),
    ]
