# Generated by Django 2.0.4 on 2019-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_acoustics',
            field=models.BooleanField(default=False, verbose_name='Isolamento acústico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_actors',
            field=models.BooleanField(default=False, verbose_name='Animadores'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_aircon',
            field=models.BooleanField(default=False, verbose_name='Ar Condicionado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_generator',
            field=models.BooleanField(default=False, verbose_name='Gerador de energia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_handicapped_acess',
            field=models.BooleanField(default=False, verbose_name='Acessível para deficientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_plays',
            field=models.BooleanField(default=False, verbose_name='Gincanas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_valet',
            field=models.BooleanField(default=False, verbose_name='Manobrista e/ou valet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeadditionalinformation',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wi-Fi'),
            preserve_default=False,
        ),
    ]
