# Generated by Django 2.0.5 on 2018-07-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='menu',
            field=models.FileField(blank=True, upload_to='place/menu', verbose_name='Menu'),
        ),
    ]
