# Generated by Django 2.0.4 on 2018-07-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0002_auto_20180718_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=2048, verbose_name='Descrição'),
        ),
    ]
