# Generated by Django 2.0.4 on 2019-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0002_auto_20190807_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cancellation_policy',
            field=models.CharField(default='flexivel', max_length=128, verbose_name='Video URL'),
            preserve_default=False,
        ),
    ]
