# Generated by Django 2.0.4 on 2018-08-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0003_auto_20180803_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Descrição'),
        ),
    ]
