# Generated by Django 2.0.4 on 2018-07-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0003_auto_20180722_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_unavailability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='is_authorized_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
