# Generated by Django 2.0.4 on 2019-08-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0003_place_cancellation_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cancellation_policy',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Video URL'),
        ),
    ]
