# Generated by Django 2.0.4 on 2018-07-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0004_auto_20180722_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_finished_basic',
            field=models.BooleanField(default=False),
        ),
    ]
