# Generated by Django 2.0.4 on 2019-09-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0004_auto_20190812_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='cancellation_policy',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Política de Cancelamento'),
        ),
    ]
