# Generated by Django 2.0.4 on 2018-09-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0005_placephoto_is_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='size',
        ),
    ]
