# Generated by Django 2.0.4 on 2018-10-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0006_remove_place_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='visualization',
        ),
        migrations.AddField(
            model_name='place',
            name='fature',
            field=models.FloatField(default=0, verbose_name='Visualizações'),
        ),
    ]
