# Generated by Django 2.0.4 on 2018-10-27 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0007_auto_20181027_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='fature',
            new_name='feature',
        ),
    ]
