# Generated by Django 2.0.4 on 2018-10-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0010_auto_20181027_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placefeature',
            name='reservation_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='placefeature',
            name='reservation_factor_firstday',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='placefeature',
            name='review_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='placefeature',
            name='review_factor_firstday',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='placefeature',
            name='view_factor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='placefeature',
            name='view_factor_firstday',
            field=models.FloatField(default=0),
        ),
    ]
