# Generated by Django 2.0.4 on 2018-10-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0012_auto_20181029_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placefeature',
            old_name='view_factor',
            new_name='visualization_factor',
        ),
        migrations.RenameField(
            model_name='placefeature',
            old_name='view_factor_firstday',
            new_name='visualization_factor_firstday',
        ),
    ]
