# Generated by Django 2.0.4 on 2018-10-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0013_auto_20181029_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placevisualization',
            name='creation',
            field=models.DateTimeField(),
        ),
    ]
