# Generated by Django 2.0.4 on 2018-11-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0014_auto_20181029_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('number_people', models.IntegerField(default=0, verbose_name='Número de pessoas')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
    ]
