# Generated by Django 2.0.4 on 2018-11-02 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0016_remove_placeprice_place'),
        ('placereservation', '0007_auto_20181102_1702'),
        ('buyerprofile', '0010_auto_20181102_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlacePrice',
        ),
    ]
