# Generated by Django 2.0.4 on 2018-11-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0019_auto_20181109_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='period_late_begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='period_late_end',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='period_soon_begin',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='period_soon_end',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
