# Generated by Django 2.0.4 on 2018-11-10 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0020_auto_20181109_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='period_late_begin',
        ),
        migrations.RemoveField(
            model_name='place',
            name='period_late_end',
        ),
        migrations.RemoveField(
            model_name='place',
            name='period_soon_begin',
        ),
        migrations.RemoveField(
            model_name='place',
            name='period_soon_end',
        ),
    ]
