# Generated by Django 2.0.4 on 2018-11-10 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0021_auto_20181109_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='period_late_begin',
            field=models.TimeField(default=datetime.datetime(2018, 11, 9, 23, 34, 30, 333450)),
        ),
        migrations.AddField(
            model_name='place',
            name='period_late_end',
            field=models.TimeField(default=datetime.datetime(2018, 11, 9, 23, 34, 30, 333450)),
        ),
        migrations.AddField(
            model_name='place',
            name='period_soon_begin',
            field=models.TimeField(default=datetime.datetime(2018, 11, 9, 23, 34, 30, 333450)),
        ),
        migrations.AddField(
            model_name='place',
            name='period_soon_end',
            field=models.TimeField(default=datetime.datetime(2018, 11, 9, 23, 34, 30, 333450)),
        ),
    ]
