# Generated by Django 2.0.4 on 2018-11-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0022_auto_20181109_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='period_late_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='period_late_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='period_soon_begin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='period_soon_end',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
