# Generated by Django 2.0.4 on 2018-11-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0023_auto_20181110_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_finished_payment',
            field=models.BooleanField(default=False),
        ),
    ]
