# Generated by Django 2.0.4 on 2018-12-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0024_place_has_finished_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.CharField(max_length=1024, verbose_name='Descrição'),
        ),
    ]
