# Generated by Django 2.0.4 on 2018-12-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0026_placelove'),
    ]

    operations = [
        migrations.AddField(
            model_name='placelove',
            name='creation',
            field=models.DateTimeField(auto_now_add=True, default='2010-01-01'),
            preserve_default=False,
        ),
    ]
