# Generated by Django 2.0.4 on 2019-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0027_placelove_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprovisory',
            name='photo',
            field=models.FileField(max_length=512, upload_to='place/photoprovisory', verbose_name='Foto'),
        ),
    ]
