# Generated by Django 2.0.4 on 2019-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0030_auto_20190425_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoprovisory',
            name='photo',
            field=models.ImageField(max_length=10485760, upload_to='place/photoprovisory', verbose_name='Foto'),
        ),
    ]
