# Generated by Django 2.0.4 on 2019-05-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0031_auto_20190425_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Detalhes'),
        ),
    ]
