# Generated by Django 2.0.4 on 2019-05-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0032_place_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='details',
        ),
    ]
