# Generated by Django 2.0.4 on 2018-09-03 12:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0004_auto_20180803_0837'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placecore.Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 9, 39, 22, 379083), verbose_name='Datetime'),
        ),
    ]
