# Generated by Django 2.0.4 on 2018-09-03 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20180903_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='texto',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 12, 5, 21, 95015), verbose_name='Datetime'),
        ),
    ]
