# Generated by Django 2.0.4 on 2018-09-03 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20180903_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 3, 13, 1, 5, 104933), verbose_name='Datetime'),
        ),
    ]
