# Generated by Django 2.0.4 on 2018-09-16 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20180903_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 16, 16, 2, 11, 846633), verbose_name='Datetime'),
        ),
    ]
