# Generated by Django 2.0.4 on 2018-10-27 06:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181027_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 3, 11, 7, 930795), verbose_name='Datetime'),
        ),
    ]
