# Generated by Django 2.0.4 on 2018-10-27 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20181027_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 27, 4, 36, 28, 939060), verbose_name='Datetime'),
        ),
    ]
