# Generated by Django 2.0.4 on 2018-10-29 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20181027_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 12, 25, 24, 521331), verbose_name='Datetime'),
        ),
    ]
