# Generated by Django 2.0.4 on 2018-10-29 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20181029_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 12, 46, 11, 376136), verbose_name='Datetime'),
        ),
    ]
