# Generated by Django 2.0.4 on 2018-10-29 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_auto_20181029_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 12, 50, 3, 110657), verbose_name='Datetime'),
        ),
    ]
