# Generated by Django 2.0.4 on 2018-10-29 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_auto_20181029_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 29, 13, 10, 24, 439937), verbose_name='Datetime'),
        ),
    ]
