# Generated by Django 2.0.4 on 2018-11-01 05:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_auto_20181029_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 2, 50, 47, 421416), verbose_name='Datetime'),
        ),
    ]
