# Generated by Django 2.0.4 on 2018-11-01 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_auto_20181101_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 1, 3, 22, 59, 982128), verbose_name='Datetime'),
        ),
    ]
