# Generated by Django 2.0.4 on 2018-11-02 19:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20181101_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 16, 41, 35, 932390), verbose_name='Datetime'),
        ),
    ]
