# Generated by Django 2.0.4 on 2018-11-02 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_auto_20181102_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 16, 52, 53, 75034), verbose_name='Datetime'),
        ),
    ]
