# Generated by Django 2.0.4 on 2018-11-02 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_auto_20181102_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 17, 2, 36, 450814), verbose_name='Datetime'),
        ),
    ]
