# Generated by Django 2.0.4 on 2018-11-02 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_auto_20181102_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 17, 8, 32, 299410), verbose_name='Datetime'),
        ),
    ]
