# Generated by Django 2.0.4 on 2018-11-02 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_auto_20181102_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 2, 17, 10, 45, 733928), verbose_name='Datetime'),
        ),
    ]
