# Generated by Django 2.0.4 on 2019-09-28 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('email', models.CharField(max_length=64, verbose_name='E-mail')),
                ('cellphone', models.CharField(max_length=64, verbose_name='Celular')),
                ('cpf', models.CharField(max_length=32, verbose_name='CPF')),
                ('cnpj', models.CharField(max_length=32, verbose_name='CNPJ')),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.CharField(blank=True, max_length=64, null=True, verbose_name='Secret Key')),
                ('accepts_newsletter', models.BooleanField()),
                ('has_finished_payment', models.BooleanField(default=False)),
                ('pagarme_id', models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ID Pagarme')),
                ('bank_code', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código do Banco')),
                ('agency', models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Agência')),
                ('account', models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Conta Bancária')),
                ('account_type', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Tipo de Conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
