# Generated by Django 2.0.4 on 2018-08-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='cellphone',
            field=models.CharField(default=1, max_length=64, verbose_name='Celular'),
            preserve_default=False,
        ),
    ]
