# Generated by Django 2.0.4 on 2018-08-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0002_sellerprofile_cellphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='accepts_newsletter',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
