# Generated by Django 2.0.4 on 2018-11-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0003_sellerprofile_accepts_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='account_type',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código do Banco'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='has_finished_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nome'),
        ),
    ]
