# Generated by Django 2.0.4 on 2018-11-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0004_auto_20181121_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerprofile',
            name='account',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='sellerprofile',
            name='bank_code',
        ),
    ]
