# Generated by Django 2.0.4 on 2018-11-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0005_auto_20181121_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='account',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Conta Bancária'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='account_type',
            field=models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=5, null=True, verbose_name='Agência'),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='bank_code',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Código do Banco'),
        ),
    ]
