# Generated by Django 2.0.4 on 2018-11-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0006_auto_20181121_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='pagarme_id',
            field=models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='ID Pagarme'),
        ),
    ]
