# Generated by Django 2.0.4 on 2018-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerprofile', '0007_sellerprofile_pagarme_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='pagarme_id',
            field=models.CharField(blank=True, default='', max_length=64, null=True, verbose_name='ID Pagarme'),
        ),
    ]
