# Generated by Django 2.0.4 on 2018-07-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buyerprofile', '0001_initial'),
        ('placereservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('rate_infraestructure', models.IntegerField(blank=True, null=True)),
                ('rate_rides', models.IntegerField(blank=True, null=True)),
                ('rate_cost_benefit', models.IntegerField(blank=True, null=True)),
                ('rate_attendance', models.IntegerField(blank=True, null=True)),
                ('rate_children_opinion', models.IntegerField(blank=True, null=True)),
                ('buyerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerprofile.BuyerProfile')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlaceReservation')),
            ],
        ),
    ]
