# Generated by Django 2.0.4 on 2018-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='rate_attendance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rate_children_opinion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rate_cost_benefit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rate_infraestructure',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placereview',
            name='rate_rides',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
