# Generated by Django 2.0.4 on 2018-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereview', '0003_auto_20181027_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='creation',
            field=models.DateTimeField(),
        ),
    ]
