# Generated by Django 2.0.4 on 2019-04-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereview', '0004_auto_20181029_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placereview',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
