# Generated by Django 2.0.4 on 2019-07-20 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placecore', '0001_initial'),
        ('buyerprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('value_min', models.FloatField()),
                ('name', models.CharField(max_length=32)),
                ('description_long', models.CharField(max_length=2048)),
                ('description', models.CharField(max_length=2048)),
                ('capacity_min', models.IntegerField()),
                ('capacity_max', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyerprofile.BuyerProfile')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
                ('placeprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlacePrice')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceSazonality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('modifier', models.IntegerField(blank=True, max_length=5, null=True)),
                ('period', models.CharField(max_length=4, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceUnavailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=4)),
                ('day', models.DateField()),
                ('repeat', models.CharField(blank=True, max_length=16, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
        migrations.AddField(
            model_name='placereservation',
            name='unavailability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlaceUnavailability'),
        ),
    ]
