# Generated by Django 2.0.4 on 2019-10-01 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereservation',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='placereservation',
            name='pagarme_transaction',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
