# Generated by Django 2.0.4 on 2018-08-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeprice',
            name='number_people',
            field=models.IntegerField(default=0, verbose_name='Número de pessoas'),
        ),
    ]
