# Generated by Django 2.0.4 on 2019-08-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0002_placesazonality'),
    ]

    operations = [
        migrations.AddField(
            model_name='placesazonality',
            name='period',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
