# Generated by Django 2.0.4 on 2019-11-18 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0002_auto_20191001_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereservation',
            name='value',
            field=models.FloatField(default=450.09),
            preserve_default=False,
        ),
    ]
