# Generated by Django 2.0.4 on 2018-08-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0003_placereservation_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placereservation',
            name='place',
        ),
    ]
