# Generated by Django 2.0.4 on 2018-08-26 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0004_auto_20180803_0837'),
        ('placereservation', '0004_remove_placereservation_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereservation',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placecore.Place'),
            preserve_default=False,
        ),
    ]
