# Generated by Django 2.0.4 on 2019-09-04 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0004_auto_20190812_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereservation',
            name='pagarme_transaction',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
