# Generated by Django 2.0.4 on 2018-11-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0005_placereservation_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeprice',
            name='place',
        ),
        migrations.AlterField(
            model_name='placereservation',
            name='placeprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.PlacePrice'),
        ),
        migrations.DeleteModel(
            name='PlacePrice',
        ),
    ]
