# Generated by Django 2.0.4 on 2019-09-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0005_placereservation_pagarme_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='placereservation',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
