# Generated by Django 2.0.4 on 2018-11-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0016_remove_placeprice_place'),
        ('placereservation', '0006_auto_20181102_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('number_people', models.IntegerField(default=0, verbose_name='Número de pessoas')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placecore.Place')),
            ],
        ),
        migrations.AlterField(
            model_name='placereservation',
            name='placeprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlacePrice'),
        ),
    ]
