# Generated by Django 2.0.4 on 2018-11-02 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placecore', '0016_remove_placeprice_place'),
        ('placereservation', '0006_auto_20181102_1641'),
    ]

    operations = [

        migrations.AlterField(
            model_name='placereservation',
            name='placeprice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placereservation.PlacePrice'),
        ),
    ]
