# Generated by Django 2.0.4 on 2018-11-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0007_auto_20181102_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeprice',
            name='value',
        ),
        migrations.AlterField(
            model_name='placeprice',
            name='number_people',
            field=models.IntegerField(verbose_name='Número de pessoas'),
        ),
    ]
