# Generated by Django 2.0.4 on 2018-11-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0010_auto_20181110_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeprice',
            name='capacity_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeprice',
            name='capacity_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
