# Generated by Django 2.0.4 on 2018-11-14 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0011_auto_20181110_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeunavailability',
            name='datetime_begin',
        ),
        migrations.RemoveField(
            model_name='placeunavailability',
            name='datetime_end',
        ),
    ]
