# Generated by Django 2.0.4 on 2018-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0012_auto_20181114_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeunavailability',
            name='period',
            field=models.CharField(default='min', max_length=4),
        ),
    ]
