# Generated by Django 2.0.4 on 2018-12-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0014_auto_20181115_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeunavailability',
            name='repeat',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
