# Generated by Django 2.0.4 on 2019-05-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0015_placeunavailability_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeprice',
            name='details',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Detalhes'),
        ),
        migrations.AlterField(
            model_name='placeprice',
            name='description',
            field=models.CharField(max_length=256),
        ),
    ]
