# Generated by Django 2.0.4 on 2019-05-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0016_auto_20190529_0712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placeprice',
            old_name='description',
            new_name='description_long',
        ),
    ]
