# Generated by Django 2.0.4 on 2019-05-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0019_auto_20190529_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeprice',
            name='description_long',
            field=models.CharField(default='aaewf wefawef', max_length=256),
            preserve_default=False,
        ),
    ]
