# Generated by Django 2.0.4 on 2019-05-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placereservation', '0020_auto_20190529_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeprice',
            name='value_min',
            field=models.FloatField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeprice',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='placeprice',
            name='description_long',
            field=models.CharField(max_length=2048),
        ),
    ]
